tests: fix exception policy midstream tests - v1
OISF/suricata-verify pull request #1025
Opened 2022-12-02 01:04 UTC by jufajardini

From what I understand, the README file description for the 'bypass' (`midstream-05`) test was wrong, and the test for the 'pass-flow' (`midstream-04`) wasn't actually acting as expected due to not having midstream set to true...

2022-12-26 15:20 UTC, catenacyber requested changes
Typo to fix ;-)

2022-12-26 15:20 UTC, catenacyber commented on tests/exception-policy-midstream-05/test.yaml
> +- --set stream.midstrea=true
typo missing m

2022-12-26 15:20 UTC, catenacyber commented on tests/exception-policy-midstream-05/README.md
> +We expect to have no ``alert`` or ``http`` events logged, as the flow will
s/or/neither/ ?

2023-01-03 21:37 UTC, jufajardini commented on tests/exception-policy-midstream-05/README.md
> +We expect to have no ``alert`` or ``http`` events logged, as the flow will
My Grammarly disagrees '-'

2023-01-03 21:40 UTC, jufajardini commented
Replaced by: https://github.com/OISF/suricata-verify/pull/1053

2023-01-03 21:40 UTC, closed without merging