tls: add test for tls keywords v6
OISF/suricata-verify pull request #1108
Opened 2023-02-02 00:48 UTC by hsadia538

Previous PR : https://github.com/OISF/suricata-verify/pull/1106
Describe Changes:

- Update README for `tls.subject`

2023-02-08 08:12 UTC, inashivb requested changes
Nice job! :)
Looking good overall. Left some nit comments inline.
Also, could we club these all under a tls folder to organize them better? Thanks!

2023-02-08 08:12 UTC, inashivb commented on tests/tls-subject/tls.rules
> +alert tls any any -> any any (msg:"TLS subject keyword"; tls.cert_subject; content:"C=FR, ST=IDF, L=Paris, O=Stamus, CN=SELKS"; sid:2; rev:1;)
nit: Please mention the right keyword in msg

2023-02-08 08:12 UTC, inashivb commented on tests/tls-subject/tls.rules
> +#tests tls new keyword tls.cert_subject
nit: space bw # and the rest of the string

2023-02-08 08:12 UTC, inashivb commented on tests/tls-issuerdn/test.yaml
> +    - HAVE_LIBJANSSON
It is enabled by default and does not need to be mentioned anymore.

2023-02-08 08:12 UTC, inashivb commented on tests/tls-subject/test.yaml
> +pcap: ../tls/tls.pcap
nice. I had forgotten about this altogether. :)

2023-02-08 10:24 UTC, hsadia538 commented on tests/tls-issuerdn/tls.rules
> +alert tls any any -> any any (msg:"TLS issuerDN keyword"; tls.cert_issuer; content:"C=FR, ST=IDF, L=Paris, O=Stamus, CN=SELKS"; sid:2; rev:1;)
> Nice job! :) Looking good overall. Left some nit comments inline. Also, could we club these all under a tls folder to organize them better? Thanks!

There is already another folder called `tls` in the tests directory. Should I move these there or still create a new one?

2023-02-08 11:48 UTC, jufajardini commented on tests/tls-issuerdn/tls.rules
> +alert tls any any -> any any (msg:"TLS issuerDN keyword"; tls.cert_issuer; content:"C=FR, ST=IDF, L=Paris, O=Stamus, CN=SELKS"; sid:2; rev:1;)
I'd say moving them there is fine.

2023-02-08 13:46 UTC, hsadia538 commented on tests/tls-issuerdn/tls.rules
> +alert tls any any -> any any (msg:"TLS issuerDN keyword"; tls.cert_issuer; content:"C=FR, ST=IDF, L=Paris, O=Stamus, CN=SELKS"; sid:2; rev:1;)
Sorry my bad! Its not a folder having other folders but a folder containing tests for `tls_cert_issuer` keyword.
I can make another folder called `tls-keywords` or something else for my PR but do you think its bit unorganized with some tests being in tls folder and then some tests in mine?

2023-02-08 15:05 UTC, jufajardini commented on tests/tls-issuerdn/tls.rules
> +alert tls any any -> any any (msg:"TLS issuerDN keyword"; tls.cert_issuer; content:"C=FR, ST=IDF, L=Paris, O=Stamus, CN=SELKS"; sid:2; rev:1;)
I see, sorry, I should have checked better, too. I've noticed that there are other `tls` tests that are also for keywords, though. 
Maybe we could create a folder in which to add all tests related to the `tls_cert_issuer` and add subfolders there - the current `tls` folder would be there, renamed, as well as your related test. And we could probably put all `tls` tests under a `tls` folder...

2023-02-09 11:21 UTC, hsadia538 commented
followed by #1118

2023-02-09 11:21 UTC, closed without merging