Mqtt frames v3
OISF/suricata-verify pull request #1112
Opened 2023-02-03 14:44 UTC by hsadia538

Ticket: https://redmine.openinfosecfoundation.org/issues/5731

Previous PR: #1065 

Describe changes:
- Add tests for mqtt frames for truncated messages

Requires: https://github.com/OISF/suricata/pull/8513

2023-02-09 21:07 UTC, jufajardini requested changes
I have added a few comments.  :)
Especially for the truncated test checks, I would like us to check on the frame length, too, so we can ensure things are being calculated as expected.
I am again wondering if we should have a special type for truncated frames, as, for instance, the length for the pdu frame in such case isn't the actual pdu length, just the max that suricata will process, as per MQTT standards.
So, having a truncated frame might let people know what to expect in such cases. Maybe in such circumstances, we could have a `trunc_data` frame instead of a `data` frame?

2023-02-09 21:09 UTC, hsadia538 commented on tests/mqtt-frames-truncated/test.yaml
> +requires:
alright

2023-02-09 21:10 UTC, hsadia538 commented
> I have added a few comments. :) Especially for the truncated test checks, I would like us to check on the frame length, too, so we can ensure things are being calculated as expected. I am again wondering if we should have a special type for truncated frames, as, for instance, the length for the pdu frame in such case isn't the actual pdu length, just the max that suricata will process, as per MQTT standards. So, having a truncated frame might let people know what to expect in such cases. Maybe in such circumstances, we could have a `trunc_data` frame instead of a `data` frame?

Sure I can do that . Will update this PR after the new frames PR

2023-02-10 12:20 UTC, hsadia538 commented
> I have added a few comments. :) Especially for the truncated test checks, I would like us to check on the frame length, too, so we can ensure things are being calculated as expected. I am again wondering if we should have a special type for truncated frames, as, for instance, the length for the pdu frame in such case isn't the actual pdu length, just the max that suricata will process, as per MQTT standards. So, having a truncated frame might let people know what to expect in such cases. Maybe in such circumstances, we could have a `trunc_data` frame instead of a `data` frame?

Do you also think that we should Have `trunc_pdu` as well along with `trunc_data` or just `trunc_data`

2023-02-10 14:05 UTC, jufajardini commented
> > I have added a few comments. :) Especially for the truncated test checks, I would like us to check on the frame length, too, so we can ensure things are being calculated as expected. I am again wondering if we should have a special type for truncated frames, as, for instance, the length for the pdu frame in such case isn't the actual pdu length, just the max that suricata will process, as per MQTT standards. So, having a truncated frame might let people know what to expect in such cases. Maybe in such circumstances, we could have a `trunc_data` frame instead of a `data` frame?
> 
> Do you also think that we should Have `trunc_pdu` as well along with `trunc_data` or just `trunc_data`

🤔  What about asking the others about this?

2023-02-13 10:30 UTC, hsadia538 commented
followed by #1123

2023-02-13 10:30 UTC, closed without merging