Filemagic keywords v1
OISF/suricata-verify pull request #1125
Opened 2023-02-14 13:41 UTC by hsadia538

Describe Changes:

- Add tests for `filemagic` keyword
- Add tests for file_data `prefilter` keyword.

2023-02-15 21:07 UTC, jufajardini requested changes
Congrats on yet another PR :)

I noticed that there are no tests for `file.data` and `prefilter`. As I couldn't find any in our current SV tests, can you please add rules for that, too?

2023-02-17 10:51 UTC, hsadia538 commented on tests/file-magic-keywords/test.yaml
> +            alert.signature_id: 1
We have seperate tests for filestore in other folders. do we still need them here?

2023-02-17 14:47 UTC, hsadia538 commented
followed by #1127

2023-02-17 14:47 UTC, closed without merging

2023-02-17 15:07 UTC, jufajardini commented on tests/file-magic-keywords/test.yaml
> +            alert.signature_id: 1
I usually don't think it's a bad idea to be redundant in this aspect, but I'd say that's not mandatory for this task.