smtp-eve: fix filesize and version check
OISF/suricata-verify pull request #1142
Opened 2023-03-10 05:40 UTC by inashivb

Earlier, the CRLFs that were a part of the file were also stripped off as a part of finding and stripping the delimiters in the MIME handler. This was fixed as a part of
https://redmine.openinfosecfoundation.org/issues/5725. This patch fixes the test too to reflect the fix.

Ticket: [5821](https://redmine.openinfosecfoundation.org/issues/5821)

Previous PR: #1139 

Changes since v1:
- remove min-version check as it's redundant now

2023-03-15 15:08 UTC, catenacyber requested changes
Overall good, but may be more aggressive deletion, right ?

2023-03-15 15:08 UTC, catenacyber commented
By the way, `smtp-file-data-02` seems ok already

2023-03-16 05:02 UTC, inashivb commented on tests/smtp-eve/test.yaml
> -    version: 6.0.0 # FIXME ref: https://redmine.openinfosecfoundation.org/issues/5821
This is a `fileinfo` event and the  previous one is `smtp` event. They do share many common fields indeed

2023-03-16 05:17 UTC, inashivb commented
> By the way, `smtp-file-data-02` seems ok already

Yep. Because you fixed it 😉 https://github.com/OISF/suricata-verify/commit/12e3769b6b14b2ff090049bec11eabd5ec526f47

2023-03-16 14:20 UTC, catenacyber commented on tests/smtp-eve/test.yaml
> -    version: 6.0.0 # FIXME ref: https://redmine.openinfosecfoundation.org/issues/5821
indeed

2023-03-16 14:20 UTC, catenacyber approved these changes
Good for me

2023-03-30 05:55 UTC, inashivb commented
Your PR was merged as a part of https://github.com/OISF/suricata-verify/pull/1156. Thank you for your contribution! :)

2023-03-30 05:55 UTC, closed without merging