dhcp: SV Test to validate dhcp option 60 is being logged
OISF/suricata-verify pull request #1355
Opened 2023-08-19 17:26 UTC by yatink

## Feature 4587

This PR adds a test to validate that dhcp option 60 is being logged in dhcp extended logging mode. 

Redmine ticket: [4587](https://redmine.openinfosecfoundation.org/issues/4587)

2023-08-21 07:11 UTC, inashivb requested changes
Hi @yatink ! Nice job making changes. :)
A few small changes to be made:
1. Please make sure there is just one commit in this PR for this issue. Squash the fix with the main commit.
2. Drop `SV Test to` from the commit message

2023-08-21 07:11 UTC, inashivb commented on tests/dhcp-eve-extended-option-60/test.yaml
> +# *** Add configuration here ***
Could you please remove this line and add
```
requires:
  min-version: 7
```
to make sure this only runs on 7 as this feature has just been added?

2023-08-21 11:29 UTC, yatink commented
@inashivb, can I squash the commits and force push to this branch itself or should I open a new PR ?

2023-08-23 10:58 UTC, inashivb commented
> Force pushing for now...happy to put my changes into a new branch and open a new PR if that's preferable.

That's always preferable. ;)

2023-08-23 21:08 UTC, yatink commented
> > Force pushing for now...happy to put my changes into a new branch and open a new PR if that's preferable.
> 
> That's always preferable. ;)

Got it ! I'll create a new one.

2023-08-23 21:08 UTC, closed without merging

2023-08-23 21:13 UTC, yatink commented
Continued in https://github.com/OISF/suricata-verify/pull/1359