tests: add a test for bug 6278 v3
OISF/suricata-verify pull request #1413
Opened 2023-10-06 07:15 UTC by lukashino

PR tests for "run-as":
- non-existent user
- NULL user (empty user string)

Follow-up of https://github.com/OISF/suricata-verify/pull/1412

Changes from the previous PR:
- new docs
- min-version

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6278

2023-10-09 14:17 UTC, jufajardini approved these changes
Overall structure looks good to me, changing review status only because if the Error message is changed, this will need update, too.

2023-11-18 06:05 UTC, victorjulien requested changes
needs rebase

2023-11-23 13:57 UTC, catenacyber commented
@lukashino looks like this was merged already, right ?
Could you close this PR then ?

2023-12-22 09:50 UTC, lukashino commented
Indeed, sorry forgot about this.

2023-12-22 09:50 UTC, closed without merging