tests: add ethernet eve test
OISF/suricata-verify pull request #1449
Opened 2023-10-30 20:45 UTC by regit

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6405

2023-10-31 10:58 UTC, regit commented
I've just added one commit to cover more protocol (http and fileinfo). I'm stopping there. Sorry for update on live MR.

2023-11-08 14:38 UTC, catenacyber commented
Requires https://github.com/OISF/suricata/pull/9715

2024-01-25 10:59 UTC, catenacyber commented on tests/ethernet-eve/suricata.yaml
> +include: ../../etc/suricata-4.0.3.yaml
Really suricata4 ?

2024-01-25 10:59 UTC, catenacyber requested changes
Could you use a pcap instead of pcapng Eric ?

2024-02-25 20:16 UTC, regit commented on tests/ethernet-eve/suricata.yaml
> +include: ../../etc/suricata-4.0.3.yaml
That's what is in the etc directory
```
❯ ls etc/
classification.config  reference.config  suricata-3.1.2.yaml  suricata-4.0.3.yaml
```

2024-02-25 20:25 UTC, regit commented
replaced by #1667

2024-02-25 20:25 UTC, closed without merging