tests: add rule type check for flowbits v7
OISF/suricata-verify pull request #1529
Opened 2023-12-08 19:04 UTC by hadiqaalamdar

Task #6309

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6309
Previous PR: https://github.com/OISF/suricata-verify/pull/1526

Suricata PR: https://github.com/OISF/suricata/pull/10018

Output from console:
```
===> flowbits: Sub test #11: FAIL : expected 1 matches; got 0 for filter {'filename': 'rules.json', 'count': 1, 'match': {'id': 11, 'lists.packet.matches[0].name': 'flowbits', 'lists.packet.matches[0].flowbits.action': 'noalert'}}
```
Output from stdout file:
```
Notice: suricata: This is Suricata version 7.0.3-dev (2fe2d8250 2023-10-19) running in USER mode [LogVersion:suricata.c:1149]
Warning: threshold-config: Error opening file: "/usr/local/etc/suricata//threshold.config": Permission denied [SCThresholdConfInitContext:util-threshold-config.c:177]
Warning: detect-flowbits: flowbit 'fb3' is checked but not set. Checked in 4 and 1 other sigs [DetectFlowbitsAnalyze:detect-flowbits.c:602]
Warning: detect-flowbits: flowbit 'fb4' is checked but not set. Checked in 5 and 0 other sigs [DetectFlowbitsAnalyze:detect-flowbits.c:602]
Warning: detect-flowbits: flowbit 'fb5' is checked but not set. Checked in 13 and 0 other sigs [DetectFlowbitsAnalyze:detect-flowbits.c:602]
```

2023-12-08 20:42 UTC, jufajardini requested changes
Or operand is there now \o\

Thanks for changing the `min-version` :)

I've noticed that the output example must be updated:
- it's indicating Suri 7, but this work is on Suri 8.
- we know that the other checks pass, so would be a good thing (and it is a good practice, too), to include an output sample of the eve rules file, showing how things are looking (although that might be a better case for the Suri PR, now that I think about it)
- What do you think of including at least one "ored" rule with three flowbits, just to showcase? ;)

2023-12-11 14:46 UTC, hadiqaalamdar commented
New PR: https://github.com/OISF/suricata-verify/pull/1532

2023-12-11 14:46 UTC, closed without merging

2023-12-12 12:32 UTC, hadiqaalamdar commented on tests/rules/flowbits/test.yaml
> +      lists.packet.matches[0].flowbits.names[1]: "fb2"
sorry, I missed this comment. I'm not sure I understand how you want me to change the "ored" rules.

2023-12-12 15:25 UTC, jufajardini commented on tests/rules/flowbits/test.yaml
> +      lists.packet.matches[0].flowbits.names[1]: "fb2"
Nothing to change in the rules themselves, just to add a check for the operand, for the cases when we expect to see it. :)

2023-12-12 15:30 UTC, hadiqaalamdar commented on tests/rules/flowbits/test.yaml
> +      lists.packet.matches[0].flowbits.names[1]: "fb2"
do you mean adding lists.packet.matches[0].flowbits.operand: "or" in the test.yaml file?

2023-12-12 15:31 UTC, jufajardini commented on tests/rules/flowbits/test.yaml
> +      lists.packet.matches[0].flowbits.names[1]: "fb2"
Yes!