tests: linktype_name test
OISF/suricata-verify pull request #1996
Opened 2024-07-31 14:13 UTC by jlucovsky

Continuation of #1993  

Issue: 6954

Ensure that the linktype_name is included in the alerts.

Updates:
- Modify existing test cases to expand the range of linktype name values.
- Remove unnecessary changes to existing tests

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6954

Suricata PR: https://github.com/OISF/suricata/pull/11564

2024-08-02 12:27 UTC, catenacyber commented on tests/decode-chdlc-01/test.yaml
> -    - filter:
Why is this diff so big ?

2024-08-02 12:27 UTC, catenacyber commented on tests/vxlan-decoder-02/test.yaml
> +
nit

2024-08-02 12:28 UTC, catenacyber commented on tests/decode-chdlc-02/suricata.yaml
> +         default-config:
Do we need all this ?

2024-08-02 12:29 UTC, catenacyber commented on tests/decode-chdlc-02/test.yaml
> +pcap: ../decode-chdlc-01/hdlc-http_1tx.pcap
Why do we need a new test ? 

We can have `min-version: 8` on a single check

2024-08-02 17:16 UTC, jufajardini requested changes
Could you please add the ticket reference to the readme files, too?

2024-08-13 13:10 UTC, jlucovsky commented
Continued in #2006

2024-08-13 13:10 UTC, closed without merging