tests/luaxform: Lua transform tests
OISF/suricata-verify pull request #2090
Opened 2024-10-10 13:49 UTC by jlucovsky

Continuation of #2044 

This commit adds tests for new Lua transform `luaxform`

- Basic transform operation
- Ensure non-existent Lua scripts are detected
- Ensure Lua scripts without transform functions are detected
- Ensure Lua scripts properly receive optional transform arguments

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/2290

2024-10-29 20:11 UTC, jufajardini requested changes
I think that maybe during rebasing there was a mishap with this commit: https://github.com/OISF/suricata-verify/pull/2090/commits/8003c9f01b79e4f5711a8572b0d9436a5423d03e

:P

2024-10-29 20:18 UTC, jufajardini commented on tests/lua/lua-transform-04/test.yaml
> +
maybe nit, but why not have a check for the alert, here, too?

2024-10-29 20:18 UTC, jufajardini commented on tests/lua/lua-transform-06/test.yaml
> +        http.url: /exec_post.php
won't there be a warning or error here that we could also check for?

2025-01-18 11:58 UTC, victorjulien commented
replaced by #2240

2025-01-18 11:58 UTC, closed without merging