createst: Allow to exclude certain fields
OISF/suricata-verify pull request #2115
Opened 2024-11-04 08:43 UTC by Nancyenos

Ticket: #4062

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4062

## Ticket
- This is a continuation of PR #997 by  @TharushiJay
-  exclude Non top-level fields fields
- updated readne
- previous pr #2110 
```
createst.py mytest mypcap --exclude-fields dest_port,tcp.ts_max_regions
```
Before:
```
 filter:
    count: 1
    match:
      app_proto: http
      dest_ip: 82.165.177.154
      event_type: flow
      flow.age: 0
      flow.alerted: false
      flow.bytes_toclient: 495
      flow.bytes_toserver: 425
      flow.pkts_toclient: 4
      flow.pkts_toserver: 6
      flow.reason: shutdown
      flow.state: closed
      proto: TCP
      src_ip: 10.16.1.11
      src_port: 54186
      tcp.ack: true
      tcp.fin: true
      tcp.psh: true
      tcp.state: closed
      tcp.syn: true
      tcp.tc_max_regions: 1
      tcp.tcp_flags: 1b
      tcp.tcp_flags_tc: 1b
      tcp.tcp_flags_ts: 1b
      tcp.ts_max_regions: 1
```
After:
```
filter:
    count: 1
    match:
      app_proto: http
      dest_ip: 82.165.177.154
      event_type: flow
      flow.age: 0
      flow.alerted: false
      flow.bytes_toclient: 495
      flow.bytes_toserver: 425
      flow.pkts_toclient: 4
      flow.pkts_toserver: 6
      flow.reason: shutdown
      flow.state: closed
      flow_id: 2019292059448498
      proto: TCP
      src_ip: 10.16.1.11
      src_port: 54186
      tcp.ack: true
      tcp.fin: true
      tcp.psh: true
      tcp.state: closed
      tcp.syn: true
      tcp.tc_max_regions: 1
      tcp.tcp_flags: 1b
      tcp.tcp_flags_tc: 1b
      tcp.tcp_flags_ts: 1b
      timestamp: 2016-07-13T22:42:07.011401+0000
```

2024-11-18 12:30 UTC, catenacyber commented on createst.py
> +        all_content_list.append(md)
nit typo added space

2024-11-18 12:33 UTC, catenacyber commented
timestamp: 2016-07-13T22:42:07.011401+0000should not be readied

2024-11-18 12:33 UTC, catenacyber commented on createst.py
> +        md = exclude_nested_fields(e)
`skip_fields` should till be used

2024-11-18 12:34 UTC, catenacyber requested changes
`skip_fields` should still be used

2024-11-22 17:43 UTC, Nancyenos commented
@catenacyber noted ...working on it

2024-11-23 11:41 UTC, Nancyenos commented
work continued in #2135

2024-11-23 11:41 UTC, closed without merging