Validate eve.json output /v1
OISF/suricata-verify pull request #427
Opened 2021-02-01 04:38 UTC by TharushiJay

Validates eve.json output using a JSON schema.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/1369

2021-02-01 21:26 UTC, jasonish commented
Nice work, this will be very useful.  I'd like to see some modifications to the output:
- Don't output anything except errors.  And when there is an error, output the test name, etc.
- If `-v` is provided, then print the "===> test_name: OK/FAIL" type thing.
- Include a summary at the end of how many eve.json files were checked and pass fail count.

2021-02-01 21:27 UTC, jasonish requested changes

2021-02-01 21:27 UTC, jasonish commented on schema.json
> +	        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+-\\d+$",
Need to handle a "+" in the timezone offset as well for timestamps like:
```2020-07-30T14:53:17.457474+0000```
this should probably do it:
```
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+[+\\-]\\d+$",
```

2021-02-01 21:27 UTC, jasonish commented on schema.json
> +	                },
minor: indenting seems off here.  vscode shift+ctrl+i seems to clean it up nicely.

2021-02-03 13:39 UTC, TharushiJay commented
Changes continued in #428

2021-02-03 13:39 UTC, closed without merging