Validate eve.json output /v2
OISF/suricata-verify pull request #428
Opened 2021-02-03 13:38 UTC by TharushiJay

Validates eve.json output using JSON schema.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/1369

Changes from last PR : 
- Changed the format of the output message
- Added a -v command line argument
- Included the (checked, passed, failed) eve.json file count summary at the end

2021-02-03 15:45 UTC, jasonish requested changes

2021-02-03 15:45 UTC, jasonish commented on check-eve.py
> +
This needs a license and copyright. You can copy it from `run.py`, but use a date of just 2021.

2021-02-03 17:01 UTC, jasonish commented
I have a few more changes I'd like to see.. Sorry, kind of defining the use-cases as we go.

If an argument is provided, for example: `check-eve /path/to/eve.json`, this script should just that single file.  But if that argument is a directory, then it should use that directory as the topdir.  If no provided, the current behaviour is good. This will allow us to use this script in other contexts outside of the suricata-verify repo.

2021-02-04 05:49 UTC, TharushiJay commented
> I have a few more changes I'd like to see.. Sorry, kind of defining the use-cases as we go.
> 
> If an argument is provided, for example: `check-eve /path/to/eve.json`, this script should just that single file. But if that argument is a directory, then it should use that directory as the topdir. If no provided, the current behaviour is good. This will allow us to use this script in other contexts outside of the suricata-verify repo.

Thanks for the feedback on the changes. It's easier for me this way, since we're increasing complexity as we go. 👍

2021-02-09 05:16 UTC, TharushiJay commented
Changes continued in #431

2021-02-09 05:16 UTC, closed without merging