Validate eve.json output /v3
OISF/suricata-verify pull request #431
Opened 2021-02-09 05:15 UTC by TharushiJay

Validates eve.json output using JSON schema.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/1369

Changes from last PR :

- Included license and copyright
- Added the use case where an argument may be provided as a single file or a directory

2021-02-09 15:25 UTC, jasonish commented
This looks a little odd when I run on a file outside the suricata-verify tree:
```
./check-eve.py  -v /var/log/suricata
```
In this case it would be better to see the whole filename.

I wonder, if we should just use the whole filename in the output.  Ideally if its running in the suricata-verify directory, we'd chop off the common prefix to be less verbose?

2021-02-09 15:26 UTC, jasonish commented
Can you also add in a test for an array..  There are eve.json records with a vlan in them.. Looks like:
```
{
  "timestamp": "2019-07-11T14:13:06.980924+0000",
  "flow_id": 1319518172542908,
  "pcap_cnt": 1,
  "event_type": "alert",
  "vlan": [
    6
  ],
```
This should always be an array.

2021-02-09 15:29 UTC, jasonish commented
What I'd like to look at next is adding this directly to run.py.  After each test in run.py, execute this script with the tests output directory as the argument.  That way we can fail the test with an `invalid json schema` error.

2021-02-09 15:29 UTC, jasonish requested changes

2021-02-09 15:29 UTC, jasonish commented on check-eve.py
> +# Copyright (C) 2017-2021 Open Information Security Foundation
This should just be 2021 as its a new file this year.

2021-02-16 18:06 UTC, TharushiJay commented
Changes continued in #440]

2021-02-16 18:06 UTC, closed without merging