Validate eve.json output /v5
OISF/suricata-verify pull request #461
Opened 2021-02-24 17:04 UTC by TharushiJay

Validates eve.json output using JSON schema.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/1369

Changes from last PR : #440

- Added `--quiet `to suppress all output
- Resolved path errors
- Threw error in `run.py` if `check-eve.py` exited with error
- Broke commit into 3

2021-02-24 18:31 UTC, jasonish requested changes
The output is still a little odd when the schema is updated to fail:
```
===> alert-distance-within-1: OK
===> alert-distance-within-1: FAILED: Invalid JSON schema
===> alert-no-3whs-established: OK
===> alert-no-3whs-established: FAILED: Invalid JSON schema
===> alert-testmyids: OK
===> alert-testmyids: FAILED: Invalid JSON schema
```
but lets focus on the other issues first.

2021-02-24 18:31 UTC, jasonish commented on run.py
> +        check_output = subprocess.call(["../suricata-verify/check-eve.py", outdir, "-q"])
We need to use TOPDIR here to get the path correct.  I can suricata-verify like `../../suricata-verify.run.py` from my Suricata source directory, and the path is not found.

2021-02-24 18:31 UTC, jasonish commented on run.py
> +            raise TestError("Invalid JSON schema")
This should be `!= 0`.

2021-02-26 17:03 UTC, closed without merging

2021-02-26 17:03 UTC, TharushiJay commented
Changes continued in #464