uricontent: add test for DetectUriSigTest02
OISF/suricata-verify pull request #621
Opened 2021-12-25 00:00 UTC by TheKharleeci

Previous PR: #619

2021-12-26 00:52 UTC, inashivb requested changes
All in all, LGTM. :)
Some nits are requested from me.
Next steps:
1. Please check if any of the other tests in `detect-uricontent.c` do something differently. If yes, add tests corresponding to them too.
2. Make a folder for all these uricontent tests in the `tests` directory here.
3. Once all the convertible C tests have been converted to s-v, delete the corresponding tests from the C file and create a PR on https://github.com/OISF/suricata for that.

That should complete the process for this one file.

2021-12-26 00:52 UTC, inashivb commented on tests/uricontent-01/test.yaml
> +# *** Add configuration here ***
nit: Please remove this line and the newline following this,

2021-12-26 00:52 UTC, inashivb commented on tests/uricontent-01/test.yaml
> +      event_type: alert
Please add the signature ID which should alert among the three rules provided.

2021-12-26 00:52 UTC, inashivb commented on tests/uricontent-01/test.yaml
> +      event_type: stats
We probably don't need the `stats` event but it doesn't hurt without the checks for other params, I think.

2021-12-30 08:52 UTC, TheKharleeci commented
Followed By: #624

2021-12-30 08:52 UTC, closed without merging