detect-flowbits/v1: add tests for detect-flowbits
OISF/suricata-verify pull request #651
Opened 2022-01-16 00:39 UTC by TheKharleeci

Adds test for FlowBitsTestSig9-11

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

2022-01-18 12:14 UTC, jufajardini requested changes
This one needs input from the other mentors, as it seems that some of the unittests require more detailed checks or more detailed rules for them to be covered by this s-v test. I've left a few thoughts in the comments, to explain why do I think that.

2022-01-18 12:14 UTC, jufajardini commented on tests/detect-flowbits/test.rules
> +alert ip any any -> any any (msg:"Flowbit unset"; flowbits:toggle,myflow2; sid:7;)
The result of this rule varies based on what was the previous state of the flowbits variable, so I think we'll have to decide first on what we want here, so we can settle on the test checks and on the rule message...
(acc to https://suricata.readthedocs.io/en/latest/rules/flow-keywords.html?#flowbits)

2022-01-18 12:14 UTC, jufajardini commented on tests/detect-flowbits/test.yaml
> +      event_type: alert
I _think_ we need more details here, as we have many rules and in the end it's not very clear which ones are matching, nor how. Some input (based on the unittests) to help deciding on that, hopefully...

Test06, Test07 and Test08:
not sure how to go about these... Maybe if we used also `noalert` to the first `flowbists:set`, then added a `content` keyword for the rule with `flowbits:toggle` and made sure the test expected that one to match for an alert? 
Test09:
expects matches from 1 and 2, but no match from 4
Test11:
expects matches from 1, 2, 3 but no match for 5
Test10:
expects matches from 1, 2, 3 and 4

2022-01-18 17:20 UTC, jasonish commented
I agree with @jufajardini, more detail needs to be in the match tests.  For example, to test `FlowBitsTestSig09`, I'd want to verify that sid 1 and 2 triggered, but that sid 4 (sid 3 from `FlowBitsTestSig09`) did not.

Then for `FlowBitsTestSig09` I'd want to verify that sid 1, 2, 3 and 4 fired.

As these both share the same pcap, I think they can all live in the test S-V test, but you may have to create more rules.

3 rules, sids 1-3 using a common prefix for the flow bits to test `Sig09`...

4 rules, sids 4-7, using a different flowbit prefix to test `Sig09` and so on.

Keeping in mind you can only test about 15 alerts per packet, but that should give you enough to replicate unit tests 9-11 here.

2022-01-30 12:48 UTC, TheKharleeci commented
Followed By: #696

2022-01-30 12:48 UTC, closed without merging