detect-hostbits/v1: convert unittests
OISF/suricata-verify pull request #660
Opened 2022-01-17 23:13 UTC by TheKharleeci

Adds test for:
- Detect-hostbits-01: HostBitsTestSig05
- Detect-hostbits-01: HostBitsTestSig07
- Detect-hostbits-01: HostBitsTestSig08

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

2022-01-18 06:46 UTC, victorjulien commented on tests/detect-hostbits/detect-hostbits-01/test.yaml
> +checks:
we should probably also add checks for sid 1 and sid 2 not generating alerts, so `count: 0`

2022-01-18 06:47 UTC, victorjulien commented on tests/detect-hostbits/detect-hostbits-02/test.yaml
> +checks:
can you add a filter for sid 1 here as well?

2022-01-18 06:48 UTC, victorjulien commented on tests/detect-hostbits/detect-hostbits-03/test.yaml
> +- filter:
sid 4 should get a check

2022-01-18 06:48 UTC, victorjulien requested changes
see comments

2022-01-19 21:52 UTC, TheKharleeci commented
Followed by: #666

2022-01-19 21:52 UTC, closed without merging