detect-file-data/v4: add tests for SMTP file data
OISF/suricata-verify pull request #663
Opened 2022-01-19 19:49 UTC by TheKharleeci

Test conversion is shown below:

smtp-file-data-01: DetectEngineSMTPFiledataTest01

smtp-file-data-02: DetectEngineSMTPFiledataTest03

Previous PR: #644 

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4938

2022-01-20 08:15 UTC, inashivb requested changes
Just one nit as of now. Just approved the builds, let's see if it passes.
Rest, LGTM! Good job! :)

2022-01-20 08:15 UTC, inashivb commented on tests/smtp-file-data/smtp-file-data-02/README.md
> +Test file_data keyword against smtp for fragmented pcaps
nit: fragmented data

2022-01-20 17:50 UTC, jufajardini commented
> Just one nit as of now. Just approved the builds, let's see if it passes. Rest, LGTM! Good job! :)

We are still getting failures for 6.0.x (and 5.0.x), but I see that the backport which we expected would fix this failure has been merged a few days ago...

2022-02-01 10:46 UTC, inashivb commented
> > Just one nit as of now. Just approved the builds, let's see if it passes. Rest, LGTM! Good job! :)
> 
> We are still getting failures for 6.0.x (and 5.0.x), but I see that the backport which we expected would fix this failure has been merged a few days ago...

Seems like some commit is still missing that affects the logged file size.

2022-02-02 09:57 UTC, TheKharleeci commented
Followed by: #708

2022-02-02 09:57 UTC, closed without merging