nfs4: add tests for readdir/setclientid records v2
OISF/suricata-verify pull request #672
Opened 2022-01-22 14:29 UTC by ghostinthehive

Previous PR: #658
S-V for unittests at https://github.com/OISF/suricata/pull/6819/commits/c4bd3cd70e3b0a2718eb404a214748780cfc4db4

2022-01-24 07:20 UTC, victorjulien commented on tests/nfs4-response-readdir/README.md
> +PCAP by Victor Julian
typo

2022-01-24 07:21 UTC, victorjulien commented on tests/nfs4-setclientid/README.md
> +PCAP by Victor Julian
typo

2022-01-24 07:23 UTC, victorjulien commented on tests/nfs4-setclientid/test.yaml
> +checks:
no nfs checks?

2022-01-24 07:23 UTC, victorjulien commented on tests/nfs4-response-readdir/test.yaml
> +checks:
no nfs checks?

2022-01-24 07:24 UTC, victorjulien requested changes
see inline comments

2022-01-24 17:01 UTC, ghostinthehive commented
> see inline comments

@victorjulien Please correct me If I'm wrong, I can see only `NFSPROC4_WRITE` being logged, all the rest is logged as `malformed_data` so I guess it means they are invalid records?

Which left me with no choice but logging these PCAPs as just `flow` events, So I'm beginning to question the need of having S-V tests for these two cases?
Or am I missing something here?

2022-08-24 11:45 UTC, catenacyber commented
@ghostinthehive what is the status here ?

2022-12-26 10:14 UTC, catenacyber commented
Closing as unfinished

2022-12-26 10:14 UTC, closed without merging