http-response-line/v1: add unittests
OISF/suricata-verify pull request #680
Opened 2022-01-26 21:49 UTC by TheKharleeci

Includes test for DetectHttpResponseLineTest02

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

2022-01-26 22:33 UTC, TheKharleeci commented
Corresponding Suricata PR: OISF/suricata#6868

2022-01-27 06:52 UTC, inashivb requested changes
Some style related changes requested from me. Rest, LGTM. Thanks! :)

2022-01-27 06:52 UTC, inashivb commented on tests/http-response-line/writepcap.py
> +    IPv6(dst='1.2.3.4', src='5.6.7.8')/TCP(sport=6666, dport=63, flags='P''A')/HTTP()/HTTPRequest(Method= 'GET',Path= '/index.html',Http_Version= 'HTTP/1.0',User_Agent='This is dummy message body',Ho
style:
- Could you please make sure there are no spaces on either side of `=` when you're adding arguments?
- Space should be there after every `,`

2022-01-27 11:13 UTC, TheKharleeci commented
Followed by: #681

2022-01-27 11:13 UTC, closed without merging