detect-flowbits/v3: add tests
OISF/suricata-verify pull request #697
Opened 2022-01-30 13:14 UTC by TheKharleeci

Adds test for FlowBitsTestSig6-11

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Previous PR: #696

2022-01-30 14:14 UTC, TheKharleeci commented
Corresponding Suricata PR: OISF/suricata#6899

2022-01-30 17:34 UTC, TheKharleeci commented
I still need to add filters for the sigs that don't alert. I'm not sure why those builds are failing.

2022-01-31 07:30 UTC, inashivb commented
> I still need to add filters for the sigs that don't alert. I'm not sure why those builds are failing.

I see
```
[1038387] 31/1/2022 -- 07:27:13 - (detect-flowbits.c:189) <Error> (DetectFlowbitParse) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - spaces not allowed in flowbit names
[1038387] 31/1/2022 -- 07:27:13 - (detect-engine-loader.c:184) <Error> (DetectLoadSigFile) -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert ip any any -> any any (msg:"Flowbit isnotset ored flowbits"; flowbits:isnotset, fb1 | fb2 ; sid:7;)" from file /home/ard/Orgs/oisf/suricata-verify/tests/detect-flowbits/test.rules at line 6
```

Flowbit ORing was not supported in `5.0.x`.. as a result of that, engine seems to think `fb1 | fb2` as one flowbit and fails because spaces are not allowed.

2022-01-31 07:30 UTC, inashivb requested changes

2022-01-31 07:30 UTC, inashivb commented on tests/detect-flowbits/test.yaml
> +- -k none
min-version: 6 would be required here..

2022-01-31 07:39 UTC, inashivb requested changes

2022-01-31 07:39 UTC, inashivb commented on tests/detect-flowbits/test.rules
> +alert ip any any -> any any (msg:"isset option"; flowbits:isset,fbt; content:"GET "; sid:13;)
I do not see any tests for `AND` op among flowbits. Please add those rules too. e.g. `isset,fb1,fb2,..`
You can read more here: https://unixia.wordpress.com/2020/05/17/more-checks-with-lesser-rules-a-flowbit-magic-tale/

2022-02-01 14:22 UTC, closed without merging