detect-pcre/v2: add tests
OISF/suricata-verify pull request #717
Opened 2022-02-07 16:14 UTC by TheKharleeci

Test conversion: 
detect-pcre-01: DetectPcreModifPTest04
detect-pcre-02: DetectPcreModifPTest05
detect-pcre-03: DetectPcreTestSig01-03
detect-pcre-04: DetectPcreTestSig09-14
detect-pcre-05: DetectPcreTestSig15-16, DetectPcreFlowvarCapture01- 03

Changes from last PR: added test for DetectPcreFlowvarCapture01- 03

Previous PR: #634

2022-02-07 17:18 UTC, TheKharleeci commented
Corresponding Suricata PR: https://github.com/OISF/suricata/pull/6942

2022-02-08 05:07 UTC, inashivb requested changes
There are still some tweaks that we need to make. Comments inline. :)

2022-02-08 15:57 UTC, jufajardini requested changes
Some comments inline. I think we need input from another mentor for some of those!

2022-02-08 15:57 UTC, jufajardini commented on tests/detect-pcre/detect-pcre-02/test.rules
> +alert http any any -> any any (msg:"Pcre modifier P (no match)"; pcre:"/DOCTYPE/P"; sid:2;)
From the original test, both rules should not alert with the first packet, but should be triggered with the second. Is there a good way to test that exact behavior in a single test, here?

2022-02-08 15:57 UTC, jufajardini commented on tests/detect-pcre/detect-pcre-04/writepcap.py
> +wrpcap('input.pcap', pkts)
Considering the unittest `DetectPcreTestSig12` I think we should have another packet here, with payload
```c
"GET / HTTP/1.0\r\nUser-Agent: Mozilla/1.0\r\n"
        "Cookie: dummoOOooooO\r\n\r\n";
 ```
for this S-V test to truthfully cover what we had there.

2022-02-08 15:57 UTC, jufajardini commented on tests/detect-pcre/detect-pcre-04/test.rules
> +alert tcp any any -> any any (content:"POST"; http_method; content:"Mozilla"; http_header; content:"dummy"; http_cookie; pcre:"/one/P"; sid:6; rev:1;)
I think this last one was actually taken from `DetectPcreTxBodyChunksTest`s Maybe it wasn't meant to be here?

2022-02-08 15:57 UTC, jufajardini commented on tests/detect-pcre/detect-pcre-05/test.rules
> +alert http any any -> any any (content:"Server: "; http_header; pcre:"/(?P<flow_ua>.*)\r\n/HR"; content:"xyz"; http_header; priority:3; sid:6;)
Is there a preferred way for checking flowvar related sids in a S-V test? I noticed that the corresponding unittests in this case have other checks than an alert check doesn't seem to convey.

2022-02-08 15:57 UTC, jufajardini commented on tests/detect-pcre/detect-pcre-05/writepcap.py
> +    IP(dst='1.2.3.4', src='5.6.7.8')/TCP(sport=6666, dport=80, flags='P''A')/"POST / HTTP/1.0\r\nUser-Agent: Mozilla/1.0\r\nCookie: dummy 1234\r\n\r\n"
The `DetectPcreFlowvarCapture` unittests have a more complete payload, and I noticed that some of the signatures in them do look for content that shows up later on in that payload (`Server`). Is it ok to miss that here?

2022-02-08 16:11 UTC, inashivb commented on tests/detect-pcre/detect-pcre-02/test.rules
> +alert http any any -> any any (msg:"Pcre modifier P (no match)"; pcre:"/DOCTYPE/P"; sid:2;)
With what I see here btw I think if fragmentation is done correctly, both the rules should alert.

2022-03-03 21:15 UTC, TheKharleeci commented
Followed By: #776

2022-03-03 21:15 UTC, closed without merging