detect-bytetest/v1: add tests
OISF/suricata-verify pull request #719
Opened 2022-02-07 21:44 UTC by TheKharleeci

detect-bytetest-02: DetectByteTestTestPacket01-05
detect-bytetest-03: DetectByteTestTestPacket06

2022-02-07 21:55 UTC, TheKharleeci commented
Corresponding Suricata PR: https://github.com/OISF/suricata/pull/6945

2022-02-08 05:17 UTC, inashivb requested changes
One small requested inline change wrt version requirements.

2022-02-08 05:17 UTC, inashivb commented on tests/detect-bytetest-03/test.rules
> +alert dns any any -> any any (msg:"Byte test against first byte"; byte_test:1,=,0x07,0,bitmask 0xF8; sid:1;)
`bitmask` was not implemented in `5.0.x`, please add a min-version check in this test for 6.

2022-02-08 09:14 UTC, TheKharleeci commented
Followed By: #720

2022-02-08 09:14 UTC, closed without merging