detect-bytetest/v2: add tests
OISF/suricata-verify pull request #720
Opened 2022-02-08 09:13 UTC by TheKharleeci

Conversion:
- detect-bytetest-02: DetectByteTestTestPacket01-05
- detect-bytetest-03: DetectByteTestTestPacket06

Changes from V1: 
Min-version added for detect-bytetest-03

Previous PR: #719

2022-02-08 09:15 UTC, TheKharleeci commented
Corresponding Suricata PR: https://github.com/OISF/suricata/pull/6945

2022-02-08 13:02 UTC, jufajardini requested changes
I think we must change the payload in the pcap for detect-bytetest-03 for proper alert count, with that one (see inline comment).

Also think since we now would have three detect-bytetest in S-V, we could move all of them to a `detect-bytetest` dir. :)

2022-02-12 22:29 UTC, TheKharleeci commented on tests/detect-bytetest-03/test.yaml
> +      alert.signature_id: 3
I tried this but it still doesn't alert

2022-02-14 09:50 UTC, jufajardini commented on tests/detect-bytetest-03/test.yaml
> +      alert.signature_id: 3
Can you share with us somewhere what you have done, might be easier to provide further guidance. It can be in private, if you prefer.

2022-02-28 22:47 UTC, TheKharleeci commented
Followed By: #769

2022-02-28 22:47 UTC, closed without merging