Add tests for nfs* frames v3
OISF/suricata-verify pull request #749
Opened 2022-02-21 14:45 UTC by ghostinthehive

Previous PR #739 
Changes from Previous PR:

- Add `content` modifier keywords for needed rules
 
Goes with https://github.com/OISF/suricata/pull/7043

2022-02-21 17:19 UTC, jufajardini requested changes
Looking good to me! Just a minor thing from my end, see inline comment :)

2022-02-21 17:19 UTC, jufajardini commented on tests/nfs2-frames/test.yaml
> +      - rust/src/nfs/nfs2.rs
I think we don't need to use that any longer, these days for Rust is not optional.

2022-02-22 02:35 UTC, inashivb commented
Another nit: I think we can drop the `S-V` in the commit message.

2022-02-22 06:27 UTC, ghostinthehive commented
Followed by #754

2022-02-22 06:27 UTC, closed without merging