lua: Test byte_extract access from match scripts
OISF/suricata-verify pull request #899
Opened 2022-07-29 13:23 UTC by jlucovsky

Continuation of #591 

Add tests for accessing byte_extract and byte_math variables from lua match scripts

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: [#2871](https://redmine.openinfosecfoundation.org/issues/2871)

Updates:
- Remove use of Lua 5.3 `string.pack` in tests
- Validate values with hex comparisons

2022-08-24 12:08 UTC, catenacyber commented
Suricata PR was merged in https://github.com/OISF/suricata/pull/7663

2022-08-24 12:24 UTC, catenacyber requested changes
Make min-version 7 so that all tests pass

2022-09-04 12:57 UTC, jlucovsky commented on tests/lua-byte-extract/test.yaml
> +    - HAVE_LUA
Added `min-version: 7`

2022-09-13 11:12 UTC, victorjulien commented
Merged in #932, thanks!

2022-09-13 11:12 UTC, closed without merging