tests: add test to verify unmatched signatures does not write to dataset
OISF/suricata-verify pull request #959
Opened 2022-10-14 11:50 UTC by norg

Suricata Verify test related to https://redmine.openinfosecfoundation.org/issues/5576

2022-10-17 10:54 UTC, inashivb requested changes
Not moved forward with this yet. Was just trying and found a complaint of rule failure by Suricata. :)

2022-10-17 10:54 UTC, inashivb commented on tests/datasets-validate-postmatch/test.rules
> +alert http any any -> $HOME_NET any (msg:"HTTP learning"; flow:established,to_client; http.content_type; content:"noone"; http.server; content:"ECS"; fast_pattern; dataset:set,http,type string,state
We should keep the filename to `http.intel` only as `output` dir doesn't exist initially and is written everytime we run the test.

2022-10-17 14:00 UTC, inashivb approved these changes
The earlier review was incorrect. This is fine but needs tweaks if run with gdb

2022-11-21 16:18 UTC, catenacyber commented
cf https://github.com/OISF/suricata/pull/8114

2023-09-28 17:35 UTC, victorjulien commented
PR is too old to restart the CI, can you resubmit?

2024-01-18 08:18 UTC, catenacyber requested changes
Rebase + Resubmit was requested

2024-06-11 15:50 UTC, closed without merging